version: "3.1"
services:
    postgresql:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: boilerplate